name: Get Repository Secrets

on:
  push:
    branches: ["test"]

jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve secrets
        id: secrets
        run: |
           curl -s -H "Authorization: Bearer ${{ secrets.MYGH_TOKEN }}" https://api.github.com/repos/josliniyda27/export-secrets/actions/secrets | jq -r '.secrets[] | "\(.name)=\(.value)"' > secrets.txt
           cat secrets.txt
        
