name: Get Repository Secrets

on:
  push:
    branches: ["test"]

jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve secrets
        id: secrets
        run: |
          echo "::set-env name=ALL_SECRETS::$(jq -r '.secrets[] | "\(.name)=\(.value)"' <(curl -s -H "Authorization: Bearer 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" https://api.github.com/repos/josliniyda27/export-secrets/actions/secrets))"
          echo $ALL_SECRETS > all_secrets.txt
        shell: bash

      - name: Print secrets
        run: |
          cat all_secrets.txt
        if: always()
