name: Get Repository Secrets

on:
  push:
    branches: ["test"]

jobs:
#Job to dynamically fetch secrets 
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve secrets
        id: secrets
        run: |
          secrets=($(curl -s -H "Authorization: Bearer ${{ secrets.MYGH_TOKEN }}" https://api.github.com/repos//josliniyda27/export-secrets/actions/secrets | jq -r '.secrets[].name')          )
          for secret_name in "${secrets[@]}"; do
            echo "${secret_name}=${secrets.${secret_name}}" >> secrets.txt
          done
           cat secrets.txt
        
